[versions]
auto-service = "1.1.1"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = "io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT"
gson = "com.google.code.gson:gson:2.10.1"
guice = "com.google.inject:guice:7.0.0"
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service"}
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service"}

# Plugin dependencies
triumph-gui = "dev.triumphteam:triumph-gui:3.1.13"
fancy-holograms = "de.oliver:FancyHolograms:2.9.0"

# Testing
junit-bom = "org.junit:junit-bom:5.12.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.1.0-alpha1"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.20.6"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter", "testcontainers-mysql", "testcontainers-mariadb"]

[plugins]
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml = "de.eldoria.plugin-yml.paper:0.8.0"
shadow = "io.github.goooler.shadow:8.1.8"